version: '3.8'

services:
    api:
        image: abhikaboy/studycafe
        ports:
            - '8000:8000'
        environment:
            - PYTHONPATH=/app
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
        restart: unless-stopped
