version: '3.8'

services:
    api:
        build: .
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        environment:
            - PYTHONPATH=/app
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        restart: unless-stopped
